[package]
name = "execsnoop"
version = "0.1.0"
authors = ["Uchio Kondo <udzura@udzura.jp>", "BCC developers"]
edition = "2018"

[dependencies]

anyhow = "1.0"
libbpf-rs = "0.6.1"
libc = "0.2"
plain = "0.2"
chrono = "0.4"
structopt = "0.3"
lazy_static = "1.4.0"